### ISSUE TITLE
Add support for generic external memory

### ISSUE THREAD

**Issue by cwoodhayes** [janjongboom/mbed-simulator#10]
This would be super helpful for fast development, especially on my team where we have more developers than we have MBEDs. It'd be awesome if there were some generic flash memory component for which you could specify memory size and call writes & reads.

**Comment by janjongboom** [comment]
@cwoodhayes Like a BlockDevice? Good idea.

**Comment by cwoodhayes** [comment]
That’d be perfect :)

**Comment by janjongboom** [comment]
Implemented in the mbed-os-5.9 branch: https://github.com/janjongboom/mbed-simulator/commit/4c79f2f9315b4423fe9f83bd4e96a7eeea3fd375 - compatible with other block devices in Mbed (such as SPIF and SD), but persisting it to local storage. Unfortunately file systems don't work yet against them (due to Emscripten hijacking the file system).

Should make it to master when Mbed OS 5.9 is out.
