### ISSUE TITLE
Error with newer emscripten version

### ISSUE THREAD

**Issue by sudobrian** [janjongboom/mbed-simulator#44]
First of all, thank you for your Mbed-simulator, and I have been using it for almost a year and had some problems when a new emscripten package is released.
But now some old emscripten is no longer supported and I cannot compile the Mbed-Simulator anymore.
The installation instruction in this github work upto 1.38.28 but this version is no longer supported and cannot be installed.
The emcc version 1.38.33 is the oldest one that can be installed online but this version brings up compilation errors, and I have tried up to the latest version (1.39.5) without luck.

Would you suggest how to install mbed-simulator with the newer emscripten package?

**Comment by janjongboom** [comment]
Hi @sudobrian, thanks for the report and happy you think it's useful. Emscripten unfortunately breaks compatibility every now and then, and changes pile up pretty quickly between new releases (e.g. https://github.com/emscripten-core/emscripten/issues/6973). Unfortunately I have left Arm since the last release of the simulator, and no-one within Arm has picked it up. This also means that I don't intend to update to a newer Emscripten compiler or Mbed OS source anytime soon.

Question though: why can't emcc 1.38.28 be installed anymore?

**Comment by sudobrian** [comment]
Hi @JanJongboom, Thank you for the response.
Emscripten has been released so often and they decided to shut down the previous repository and move to a new location. During this phase, they decided to remove all releases older than 3.38.33.
The new emsdk does not even contain history. I tried an older emdsk but 1.38.28 cannot be found.

Fortunately, I still have the previous installation with 1.38.28. So I still can use it. The only issue is that I need to carry about a 500MB zip file if I wanted to install it on another PC because it cannot be downloaded from the internet.
Since I have your answer I don't need to spend more time trying to make it work with the latest release which I kept doing myself. 
Thank you for your source code and response.

**Comment by Stavros** [comment]
Hi @sudobrian,

Just stumbled upon the same issue while trying to deploy the simulator. But there is a fix, you can install archived emsdk versions by:
" To access the historical archived versions, type 'emsdk list **--old**' "
Fix:
"emsdk install **sdk-fastcomp-1.38.23-64bit**"

Hope it helps.

**Comment by janjongboom** [comment]
Hey @Stavros, thanks a lot. I've verified this (on Ubuntu) and updated the README file.
